[package]
name = "routerosbackuptools"
version = "0.1.2"
edition = "2021"

[dependencies]
aes = "0.8.1"
anyhow = "1.0.64"
binread = "2.1.1"
binwrite = "0.2.1"
clap = "3.2.22"
ctr = "0.9.1"
hmac-sha256 = "1.1.4"
rand = "0.8.4"
rayon = "1.5.1"
rc4 = "0.1.0"
sha-1 = "0.10.0"
sha2 = "0.10.6"
